<?xml version="1.0" encoding="utf-8"?><Database Name="OES_DB" Class="OES_DALDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=MOHSIN-PC;Initial Catalog=OES_DB;User ID=sa" SettingsObjectName="OES_BAL.Properties.Settings" SettingsPropertyName="OES_DBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[user]" Member="db_users" AccessModifier="Internal">
    <Type Name="db_user" AccessModifier="Internal">
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="first_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="last_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="user_email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="user_password" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="user_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="user_gender" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="user_address" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="user_contact" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="user_image" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="created_when" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="created_by" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="edited_when" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="edited_by" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="is_firstLogin" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>